name: 定时任务

# 指定 GitHub Actions 触发的事件，包括 push 事件，定时执行 cron 事件，手动触发 workflow_dispatch 事件
on:
  push:
  schedule:
    - cron: "*/40 17-19 * * *"
    - cron: "0 2,10 * * *"
  workflow_dispatch:

# 定义访问权限，这里表示需要访问仓库的 contents 和 deployments 权限
permissions:
  contents: write
  deployments: write

jobs:
  run_code:
    runs-on: ubuntu-latest

    steps:
    - name: 检出代码
      uses: actions/checkout@v2

    - name: 设置 Python 环境
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: 安装依赖
      run: pip install requests

    - name: 运行代码
      run: |
        python ipsw.py

    - name: 创建 Deploy 文件夹
      run: mkdir -p deploy
      
    - name: 将生成的文件移动到 Deploy 文件夹
      run: |
        mv *.json deploy/

    - name: 将生成的文件复制回工作目录
      run: cp -R deploy/* $GITHUB_WORKSPACE/
      
    - name: 配置 Git
      run: |
        git config --global user.name 'y0123456789'
        git config --global user.email '52168408+y0123456789@users.noreply.github.com'
      
    - name: 提交和推送变更到 gh-pages 分支
      run: |
        git checkout -B gh-pages
        git rm -rf .
        git checkout main -- CNAME
        if [ ! -f "./CNAME" ]; then
          cp CNAME .
        fi
        cp -R deploy/* .
        git add .
        git commit -m "Update files"
        git push -f origin gh-pages
        
    # 在 GitHub Action 的工作流程中添加一个步骤，用于上传文件到服务器
    - name: 上传文件到服务器
      run: |
       # 设置服务器地址、用户名和目标目录
        SERVER_ADDRESS="124.221.182.210"
        USERNAME="root"
        REMOTE_DIR="/www"
    
       # 生成的文件路径
       FILE_PATH="path_to_generated_file"
    
       # 使用 scp 命令上传文件到服务器
       scp -r $FILE_PATH $USERNAME@$SERVER_ADDRESS:$REMOTE_DIR
